#!/bin/bash
#Build and optionally install the extra ruby utilities MBARI needs for ESP
#parameters are passed on to make
#to force complete rebuild:  buildUtils clean all
#to install for an arm host, force our ruby to load a different rbconfig.rb:
# RUBYLIB=~/armHost/usr/local/lib/ruby/1.6/arm-linux buildUtils clean install

toolDirs='mbarilib termios'
defdir=$PWD
: ${RUBY:="$defdir/miniruby -I$defdir/lib"}
for d in $toolDirs; do
  echo "Making $d:"
  cd $d
  $RUBY extconf.rb || exit 1
  make $@ || exit 1
  cd ..
done

for mktarget; do  #for things that don't have an explicit "build" operation
  [ "$mktarget" = "install" ] && {  #install IRB and MBARI misc extensions
    echo "Installing MBARI extensions..."
    $RUBY inst-mbari.rb $DESTDIR || exit 32
    break
  }
done
:
