#!/bin/bash
# configure ruby 1.8.7p352 build for arm-linux -- 11/16/12 brent@mbari.org
# for gcc x86 add:
#  -fno-stack-protector
# to CFLAGS
: ${CFLAGS:="-O2 -g -fno-stack-protector"}
: ${CXXFLAGS:=$CFLAGS}
for mod in . mbarilib termios; do 
  [ -r $mod/Makefile ] && make -C $mod MINIRUBY=miniruby distclean
done
export CC CFLAGS CXXFLAGS
rm -f config.cache configure `find ext -name Makefile` && 
autoconf && exec configure --prefix=/opt/mbari \
  --enable-mbari-api --enable-pthread --disable-ucontext $@
