#!/bin/bash
# configure ruby 1.8.7p352 build for arm-linux -- 10/20/11 brent@mbari.org
# for gcc x86 add:
#  -fno-stack-protector
# to CFLAGS
: ${CFLAGS:="-O2 -g -fno-stack-protector"}
: ${CXXFLAGS:=$CFLAGS}
[ -r Makefile ] && make MINIRUBY=miniruby distclean
export CC CFLAGS CXXFLAGS
rm -f config.cache configure `find ext -name Makefile` && 
autoconf && exec configure --prefix=/opt/mbari \
  --enable-mbari-api --enable-pthread --disable-ucontext $@
